[package]
name = "erbium"
version = "0.1.0"
authors = ["Perry Lorier <git@isomer.meta.net.nz>"]
edition = "2018"
default-run = "erbium"
description = "Network services for small/home networks"
license = "Apache-2.0"
repository = "https://github.com/isomer/erbium.git"

[dependencies]
async-std = { version = "", features = ["tokio02"] }
bytes = ""
futures = ""
futures-core = ""
futures-sink = ""
hostname = { version = "0.3.0" }
mio = { version = "0.6.20" }
netlink-packet-route = ""
netlink-sys = { version="", features=["tokio_socket"] }
nix = { version = ">=0.17, <1.0" } # We're gonna need 0.18 when it comes out
rand = ""
rusqlite = { version = "0.23.0" }
tokio-util = { version="", features= ["codec"] }
tokio = { version = "0.2", features = ["full"] }
yaml-rust = { version = "0.4" }

[lib]
name = "erbium"
path = "src/lib.rs"

[profile.release]
lto = "fat"


# We need https://github.com/nix-rust/nix/pull/1222 to build.
[patch.crates-io]
nix = { git = "https://github.com/nix-rust/nix" }
