[package]
name = "erbium"
version = "0.1.0"
authors = ["Perry Lorier <git@isomer.meta.net.nz>"]
edition = "2018"
default-run = "erbium"
description = "Network services for small/home networks"
license = "Apache-2.0"
repository = "https://github.com/isomer/erbium.git"

[features]
default=["dhcp"]
dhcp=[]
dns=[]

[dependencies]
async-std = { version = "1.6.2", features = ["tokio02"] }
bytes = "0.5.6"
futures = "0.3.5"
futures-core = "0.3.5"
futures-sink = "0.3.5"
hostname = { version = "0.3" }
mio = { version = "0.6.20" }
netlink-packet-route = "0.3"
netlink-sys = { version="0.3", features=["tokio_socket"] }
nix = { version = "0.18" }
rand = "0.7.3"
rusqlite = { version = "0.23" }
tokio-util = { version="0.3.1", features= ["codec"] }
tokio = { version = "0.2", features = ["full"] }
yaml-rust = { version = "0.4" }

[[bin]]
name="erbium-dns"
required-features=["dns"]

[[bin]]
name="erbium-dhcp"
required-features=["dhcp"]

[lib]
name = "erbium"
path = "src/lib.rs"

[profile.release]
lto = "fat"

