[package]
name = "erbium"
version = "0.1.0"
authors = ["Perry Lorier <git@isomer.meta.net.nz>"]
edition = "2018"
default-run = "erbium"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
async-std = { version = "", features = ["unstable"] }
rand = ""
nix = { version = "0.17", path="/home/perry/build/nix" }
futures = ""
mio = { version = "0.6.20" } #, features = ["udp"] }
#libc = ""
rusqlite = ""
tokio-util = { version="", features= ["codec"] }
bytes = ""
futures-core = ""
futures-sink = ""

[lib]
name = "erbium"
path = "src/lib.rs"
